# -*- coding: utf-8 -*-
# Schreibt § 0 bis § 2 des Befunds „Abgleich_Einleitung_Argumentationsstruktur_2026-09-30.md“ (Schritt 1)
import json, re
T = json.load(open('textstand_T.json', encoding='utf-8'))
mess = open('textstand_T_messung.txt', encoding='utf-8').read().split('\n')
tab = [z for z in mess if re.match(r'^B\d[ab]? S\d+ \| ', z)]
assert len(tab) == 39
L = []
w = L.append
w('# Abgleich der Einleitung mit der Argumentationsstruktur der RCT-Einleitungen — 30.09.2026')
w('')
w('Bachelorarbeit U15-Plyometrie · Arbeitsdokument, kein Manuskripttext · Stand: Schritt 1 abgeschlossen (30.09., 15:5x Sitzungsuhr), Schritte 2 bis 4 folgen in diesem Dokument')
w('')
w('Auftrag: Startprompt der Übergabe `04_Uebergaben\\Uebergabe_Abgleich_Einleitung_Argumentationsstruktur_2026-09-30.md` (§ 0), vom Verfasser am 30.09. um 14:58 Sitzungsuhr gesendet, mit dem Text der Einleitung als Anhang. Maßstab ist der Befund `02_Befunde\\Argumentationsstruktur_Einleitungen_RCT_2026-09-30.md` (MD5 `9eab5a2c…`). Skripte, Codierungen und Prüfberichte in `03_Skripte\\Abgleich_Einleitung_2026-09-30\\`. Keine Änderung am Master und an den Textvorschlägen.')
w('')
w('## 0 Stand in Kürze')
w('')
w('1. Der Master ist seit dem 26.09., 21:05 unverändert (48.791 Byte, MD5 `e35315d6…`, keine `comments.xml`). Das Messskript zählt 0 Wörter unter „1 Einleitung“ und 4.920 im Altbestand der Kapitel 2 und 3: Die Einleitung ist nicht übertragen.')
w('2. Textstand ist nach Klick der Text des Verfassers (Anhang zum Taskstart). Keine seiner vier Abweichungen vom Register wurde angekreuzt, sie sind nach dem Register zurückgesetzt. Damit ist der Textstand die Zusammensetzung nach Übergabe § 3 mit fünf Sätzen im Wortlaut des Verfassers (B1b S1, B1b S7, B3 S5, B4 S1, B4 S2) und ohne den Tanner-Satz (bisher B4 S2).')
w('3. Messung: 913 Wörter (757 ohne Belegklammern), sechs Absätze, 39 Sätze, Median 24,0, längster Satz 32 (B3 S5 und B5 S1), 26 Belegklammern in 26 Sätzen (66,7 %), 23 Quellen, 0 Semikola außerhalb von Belegklammern, 0 Abschnittsverweise, Seitenprognose rund 27,8 Seiten (Modellrechnung).')
w('4. Neu entschieden (Klicks zu Schritt 1): B2 Fassung 4 freigegeben wie D1 (D6 Nr. 1 bis 3 je a) · kombinierte Programme nicht in der Einleitung, Vormerkung 6.1 (B3 bis B5 § 8 Nr. 3 a) · § 8 Nr. 1 gegenstandslos, § 8 Nr. 2 für B3 mit dem Textstand erledigt.')
w('5. Register (Übergabe § 4): 19 Zeilen, nicht 18, zerlegt 65 Teilentscheidungen. An der Fundstelle bestätigt 52, ungenau 13, falsch 0. Im Register fehlen drei Zeilen und elf Teilentscheidungen (§ 2.4), keine davon wird vom Textstand verletzt.')
w('6. Der Textstand erfüllt das Register bis auf die fünf Sätze im Wortlaut des Verfassers. Sie weichen von freigegebenen Fassungen ab und tragen vier inhaltliche Befunde für Schritt 2: „Wirkmechanismus“ war bei Markovic & Mikulic (2010, S. 860) schon einmal als nicht gedeckt beanstandet (B1b S1) · der Präventionssatz endet unvollständig (B1b S7) · „valide“ ist in der Belegtabelle nicht nachgewiesen (B3 S5) · Tanner et al. (1966) steht als Einzelbefund ohne Population im Satz (B4 S1). Alle P-Zeilen des Kopfblocks Einleitung (1.1 bis 1.6, 3.1 bis 3.3) sind im Textstand belegt.')
w('')
w('## 1 Textstand')
w('')
w('### 1.1 Herleitung')
w('')
w('| Schritt | Ergebnis |')
w('|---|---|')
w('| Master gemessen (`Manuskriptstand_2026-09-25.py`, Fassung 3, am gestagten Master) | „Einleitung: noch Altbestand, Text der Einleitung nicht geschrieben“ · Einleitung 0 · Altbestand 2 bis 3: 4.920 Wörter, 61 Semikola, 35 Abschnittsverweise · Ausgabe `master_messung.txt` |')
w('| Zusammensetzung nach Übergabe § 3 (V) nachgemessen | 924 Wörter (768), 40 Sätze, Median 23,5, längster 32 (B5 S1), 26 Klammern, 23 Quellen, Absätze 153 · 152 · 229 · 123 · 168 · 99. Deckt sich mit § 3 |')
w('| Text des Verfassers (A), Anhang 30.09., 14:39 und 14:58, MD5 `e99e8f24…` | 814 Wörter (690), 36 Sätze, 22 Klammern, 23 Quellen, Absätze B1 180 · B2 229 · B3 154 · B4 153 · B6 98. B2 wortgleich mit B2 D1, B6 wortgleich mit B5 ohne „deshalb“ |')
w('| Klick Frage 1 (30.09., Schritt 1) | Textstand = Text des Verfassers (Empfehlung) |')
w('| Klick Frage 2 (Mehrfachauswahl) | keine Abweichung angekreuzt. Angekündigt war: „Nicht Angekreuztes setze ich nach dem Register zurück.“ Zurückgesetzt: (1) Eröffnung mit den Wettkampfanforderungen, B3-Beginn nach B1 § 1.3 (18:50, 07:00 Nr. 4) · (2) Moran et al. (2017) gestrichen (18:50) · (3) B1a und B1b vollständig, mit Illinois-Satz, Spannen-Satz, DVZ-Mechanismen, neuem DVZ-Satz und Programmsatz (07:00, 17:41) · (4) B5 S1 mit „deshalb“ (10:00) |')
w('| Klick Frage 3 | B2 Fassung 4 freigeben wie D1: zwei Anfangssätze, mit Schlusssatz (D6 Nr. 1 a, Nr. 2 a, Nr. 3 a) |')
w('| Klick Frage 4 | kombinierte Programme nicht in der Einleitung, für 6.1 vorgemerkt (B3 bis B5 § 8 Nr. 3 a) |')
w('| Folge für B3 bis B5 § 8 Nr. 1 und 2 | Nr. 1 (Einstieg B3) gegenstandslos, B3 beginnt nach B1 § 1.3 (Klick 30.09., 07:00 Nr. 4 a). Nr. 2 für B3: S2 bis S4 stehen wortgleich mit Fassung 2 im Text des Verfassers, S5 in seinem Wortlaut, mit dem Textstand-Klick erledigt |')
w('| Textstand T (`textstand_T.py`) | Satz für Satz aus V oder A, Herkunft je Satz in § 1.3. Nicht übernommene Sätze aus A in § 1.4 |')
w('')
w('### 1.2 Messung (wie `Manuskriptstand_2026-09-25.py`, Leerraum-Token mit Belegklammern)')
w('')
w('| Größe | Wert | Vorgabe oder Vergleich |')
w('|---|---|---|')
w('| Wörter | **913** (ohne Belegklammern 757) | Obergrenze 1.200 (Klick 29.09., 10:25) · V 924 · A 814 · Kern-RCTs 506 bis 927, Median 666 (Befund § 0 Nr. 4) |')
w('| Absätze | 6: B1a 153 · B1b 152 · B2 229 · B3 127 · B4 153 · B5 99 | keiner über 250 · Korpus Median 5 (2 bis 8) |')
w('| Sätze · Median · längster | 39 · 24,0 (ohne Belegklammern 19,0) · 32 (B3 S5, B5 S1) | höchstens 32 · Korpus 22,5 Sätze, Satzlänge Median 30 |')
w('| Semikola außerhalb von Belegklammern · Abschnittsverweise · Doppelpunkte | 0 · 0 · 0 | 0 |')
w('| Belegklammern · Sätze mit Beleg | 26 · 26 von 39 (66,7 %) | Korpus Median 74 % (61 bis 87 %, Befund § 2.2) |')
w('| Quellen | 23, wie V: Havanecz et al. (2026) drin, Moran et al. (2017) draußen | alle als Volltext im Ordner (Belegtabellen B1 bis B4) |')
w('| Zahlen aus dem Kennzahlenblatt | keine, Programmangabe nur „sechswöchig“ (B5 S1) | keine Studienzahlen |')
w('| Seitenprognose | rund 27,8 Seiten (Modellrechnung wie Messskript: Einleitung 913 zu 359 je Seite, Methodik bis Fazit 4.716 zu 330, Objekte 2,0, Kapitelenden 2,5, Literaturverzeichnis 49 Einträge 6,4) | Schwelle 32, Grenze 33 |')
w('')
w('### 1.3 Wortlaut mit Satznummern und Herkunft')
w('')
w('Herkunft: V = Zusammensetzung nach Übergabe § 3 (Textvorschläge B1 § 1.1 bis 1.3, B2 D1, B3 bis B5 § 1, B4 § 1), A = Text des Verfassers. Wortlaut unverändert übernommen, auch offensichtliche Versehen (Befund in Schritt 2).')
w('')
w('| Satz | Wörter | ohne Klammern | Herkunft | Wortlaut |')
w('|---|---:|---:|---|---|')
for z in tab:
    k, wo, woo, h, x = [s.strip() for s in z.split(' | ', 4)]
    w('| %s | %s | %s | %s | %s |' % (k, wo, woo, h, x))
w('')
w('Absätze zum Lesen (Satzgrenzen wie oben):')
w('')
for k, t in T['absaetze'].items():
    w('**%s** — %s' % (k, t))
    w('')
w('### 1.4 Sätze des Anhangs, die nicht im Textstand stehen')
w('')
w('| Satz in A | Grund |')
w('|---|---|')
ent = [z.strip() for z in mess[mess.index('Nicht in T (nach Frage 2 zurückgesetzt oder doppelt):') + 1:] if z.strip()]
for z in ent:
    h, g = z.split(': ', 1)
    w('| %s | %s |' % (h, g))
w('')
open('befund_teil1.md', 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print(len(L), 'Zeilen')
